set(DNNL_USE_NATIVE_ARCH ${USE_NATIVE_ARCH})

find_package(DNNL QUIET)

add_library(caffe2::dnnl INTERFACE IMPORTED)
set_property(
  TARGET caffe2::dnnl PROPERTY INTERFACE_INCLUDE_DIRECTORIES
  ${DNNL_INCLUDE_DIR})
set_property(
  TARGET caffe2::dnnl PROPERTY INTERFACE_LINK_LIBRARIES
  ${DNNL_LIBRARIES})
